import type { Metadata } from "next";
import StyledComponentsRegistry from '@/app/lib/StyledComponentsRegistry';
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import {Inter} from "next/font/google";




const inter = Inter({ subsets: ["latin"], weight : ["400", "500",  "600", "700", "800","900"]})



export const metadata: Metadata = {
  title: "Minimal-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={'$(inter.className) antialiased'}>
          {children}
        </body>
      </html>
    </>
  );
}



